spring:
  config:
    import: credentials-dev.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/springbootdemo
    driver-class-name: org.postgresql.Driver
    username: springbootdemo_owner
    password: ${DATABASE_OWNER_PASSWORD}
